baseURL: https://exegese.ch/
defaultContentLanguage: fr
disableFastRender: true
languageCode: fr-ch
title: exegese.ch

disableKinds:
- taxonomy
- taxonomyTerm
- RSS

params:
  slogan: Actualité du web protestant romand
  author: Nicolas Friedli
  images:
    - /img/facebook.jpg